// This file will be generated by Supabase CLI or manually created
// based on your database schema

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      jobs: {
        Row: {
          id: number
          title: string
          status: string
          industry: string
          price_range: string
          lead_source: string
          commission_structure: string
          team_size: string
          remote_compatible: boolean
          company_overview: string | null
          what_you_sell: string | null
          sales_process: string | null
          whats_provided: string[] | null
          not_for: string | null
          commission_breakdown: string | null
          ramp_time: string | null
          working_hours: string | null
          video_url: string | null
          created_at: string
          updated_at: string
          recruiter_id: number
          views: number
          applicants_count: number
        }
        Insert: {
          id?: number
          title: string
          status: string
          industry: string
          price_range: string
          lead_source: string
          commission_structure: string
          team_size: string
          remote_compatible: boolean
          company_overview?: string | null
          what_you_sell?: string | null
          sales_process?: string | null
          whats_provided?: string[] | null
          not_for?: string | null
          commission_breakdown?: string | null
          ramp_time?: string | null
          working_hours?: string | null
          video_url?: string | null
          created_at?: string
          updated_at?: string
          recruiter_id: number
          views?: number
          applicants_count?: number
        }
        Update: {
          id?: number
          title?: string
          status?: string
          industry?: string
          price_range?: string
          lead_source?: string
          commission_structure?: string
          team_size?: string
          remote_compatible?: boolean
          company_overview?: string | null
          what_you_sell?: string | null
          sales_process?: string | null
          whats_provided?: string[] | null
          not_for?: string | null
          commission_breakdown?: string | null
          ramp_time?: string | null
          working_hours?: string | null
          video_url?: string | null
          created_at?: string
          updated_at?: string
          recruiter_id?: number
          views?: number
          applicants_count?: number
        }
      }
      applicants: {
        Row: {
          id: number
          name: string
          email: string
          location: string
          applied_date: string
          status: string
          starred: boolean
          experience: string
          highest_ticket: string
          sales_style: string
          tools: string
          video_url: string | null
          notes: string | null
          job_id: number
          created_at: string
          updated_at: string
          avatar_url: string | null
        }
        Insert: {
          id?: number
          name: string
          email: string
          location: string
          applied_date?: string
          status: string
          starred?: boolean
          experience: string
          highest_ticket: string
          sales_style: string
          tools: string
          video_url?: string | null
          notes?: string | null
          job_id: number
          created_at?: string
          updated_at?: string
          avatar_url?: string | null
        }
        Update: {
          id?: number
          name?: string
          email?: string
          location?: string
          applied_date?: string
          status?: string
          starred?: boolean
          experience?: string
          highest_ticket?: string
          sales_style?: string
          tools?: string
          video_url?: string | null
          notes?: string | null
          job_id?: number
          created_at?: string
          updated_at?: string
          avatar_url?: string | null
        }
      }
      conversations: {
        Row: {
          id: number
          recruiter_id: number
          applicant_id: number
          job_id: number
          last_message_timestamp: string
          unread_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: number
          recruiter_id: number
          applicant_id: number
          job_id: number
          last_message_timestamp?: string
          unread_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          recruiter_id?: number
          applicant_id?: number
          job_id?: number
          last_message_timestamp?: string
          unread_count?: number
          created_at?: string
          updated_at?: string
        }
      }
      messages: {
        Row: {
          id: number
          conversation_id: number
          sender_id: number
          sender_type: string
          content: string
          timestamp: string
          read: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: number
          conversation_id: number
          sender_id: number
          sender_type: string
          content: string
          timestamp?: string
          read?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          conversation_id?: number
          sender_id?: number
          sender_type?: string
          content?: string
          timestamp?: string
          read?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      users: {
        Row: {
          id: number
          email: string
          name: string
          role: string
          created_at: string
          updated_at: string
          avatar_url: string | null
        }
        Insert: {
          id?: number
          email: string
          name: string
          role: string
          created_at?: string
          updated_at?: string
          avatar_url?: string | null
        }
        Update: {
          id?: number
          email?: string
          name?: string
          role?: string
          created_at?: string
          updated_at?: string
          avatar_url?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
